### ISSUE TITLE
Documentation: missing a `

### ISSUE THREAD

**Issue by akimd** [whitequark/ast#21]
https://github.com/whitequark/ast/blob/fcb9b91735eebf7d26b64a9767974d760958f364/lib/ast/processor/mixin.rb#L26

Cheers.

**Comment by akimd** [comment]
While at it, please note that the documentation on Github (http://whitequark.github.io/ast/frames.html) is obsolete (it still recommends subclassing the Processor for instance).

**Comment by whitequark** [comment]
Doc updated.
